# Generated by Django 4.1.2 on 2022-11-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_question_passedtest_option_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Фото'),
        ),
    ]
