# Generated by Django 4.1.2 on 2022-12-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_question_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(null=True, verbose_name='Время на выполнение'),
        ),
    ]
