# Generated by Django 4.1.2 on 2022-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.IntegerField(verbose_name='Время на выполнение'),
        ),
    ]
