# Generated by Django 4.1.2 on 2023-01-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_test_desc_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='testing.test'),
        ),
    ]
