# Generated by Django 4.1.2 on 2022-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USER'), (2, 'HR'), (3, 'ADMIN')]),
        ),
    ]
