# Generated by Django 4.1.2 on 2022-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'USER'), (1, 'HR'), (2, 'ADMIN')]),
        ),
    ]
