# Generated by Django 4.1.2 on 2022-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_resume_salary_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок резюме'),
        ),
    ]
