# Generated by Django 4.1.2 on 2023-01-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_resume_text_en_resume_text_ru_resume_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title_ru',
        ),
    ]
